[package]
name = "aws-custom-resource-provider-events"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "^1"
serde_json = "^1"
serde_derive = "^1"
ring = { version = "0.16.20" } # match tower version used by 'aws-sdk'
